### ISSUE TITLE
would be cool if shift-escape went backwards...

### ISSUE THREAD

**Issue by puterleat** [atombender/sublime_text_alternative_autocompletion#1]
Amazing though - has massively improved my chances of switching permanently! Also, how hard would it be to search all open buffers for completions? I'd always hankered after this in Textmate....

**Comment by atombender** [comment]
Backward cycling is now implemented.

I agree about being able to search other files -- but I would not be satisfied with just searching open buffers. I want autocompletion, ideally, to search all files within the same syntax scope.

That presents an interesting challenge for large projects. I work on several projects where a simple linear scan of matching files would not scale. So I'm thinking a simple inverted text index. I'm going to give it a think.
