### ISSUE TITLE
Autocomplete breaks when search box is open

### ISSUE THREAD

**Issue by ccampbell** [atombender/sublime_text_alternative_autocompletion#10]
First of all I wanted to thank you so much for this plugin.  It is really a lifesaver.  I can't stand Sublime Text's default auto complete.  I complained about it here: http://www.sublimetext.com/forum/viewtopic.php?f=3&t=5711

Anyway here is some reproduce code

```
match
match2


|
match_other
```
1. place the cursor at the position marked by `|` 
2. type mat
3. hit escape or tab to autocomplete

When you do not have the search box open it completes to "match_other" as it should since that is the closest match.  

If you press command f to bring up the search box then do the same thing it cycles through "match2", then "match", before getting to "match_other", reverting to the default crappy sublime way.

**Comment by atombender** [comment]
If I understand you correctly, I think the cause is that you don't have a key binding that closes the search box on hitting the escape key. Did you use the key bindings in the readme?

**Comment by ccampbell** [comment]
No, that's not what I mean.  I'm using the tab key for autocomplete and the bindings in the readme.  I can close the search box just fine with escape.

The problem is that when the search box is open the autocomplete reverts back to the sublime fuzzy ones and not the ones from this plugin.

**Comment by atombender** [comment]
What are your key bindings? The default key bindings assume that no "panels" or "overlays" (the search box is a panel) are open, and will revert to the default behaviour if any are open.

Probably the key bindings should not check for panels or overlays. This should fix the problem:

``` json
{ "keys": ["tab"], "command": "alternative_autocomplete", "args": {"default": "\t"}, "context":
  [
    { "key": "num_selections", "operator": "equal", "operand": 1 }
  ]
},
{ "keys": ["shift+tab"], "command": "alternative_autocomplete", "args": {"cycle": "previous"}, "context":
  [
    { "key": "num_selections", "operator": "equal", "operand": 1 }
  ]
},
{ "keys": ["tab"], "command": "indent", "context":
  [
    { "key": "text", "operator": "regex_contains", "operand": "\n" }
  ]
},
{ "keys": ["shift+tab"], "command": "unindent", "context":
  [
    { "key": "text", "operator": "regex_contains", "operand": "\n" }
  ]
},
```

**Comment by ccampbell** [comment]
Oh man.  I should have seen that.  I'm using the ones from the README which have

``` javascript
{ "key": "overlay_visible", "operator": "equal", "operand": false },
{ "key": "panel_visible", "operator": "equal", "operand": false }
```

Yeah I guess that is more needed if you are using escape for autocompletes rather than tab.

**Comment by atombender** [comment]
So the change worked satisfactorily? It doesn't screw up the tab key behaviour when the focus is inside the search box or anywhere outside the editor?

(I have already updated the readme.)

**Comment by ccampbell** [comment]
It seems fine to me.  I will let you know if I run into anything else.  Thanks!
