### ISSUE TITLE
Installation Question: How to configure?

### ISSUE THREAD

**Issue by sivabudh** [atombender/sublime_text_alternative_autocompletion#11]
Hi,

I'm following the installation instruction, and followed up to here:

To map to the escape key, like TextMate:

{ "keys": ["escape"], "command": "alternative_autocomplete", "context":
  [
    { "key": "num_selections", "operator": "equal", "operand": 1 },
    { "key": "overlay_visible", "operator": "equal", "operand": false },
    { "key": "panel_visible", "operator": "equal", "operand": false }
  ]
},
{ "keys": ["shift+escape"], "command": "alternative_autocomplete", "args": {"cycle": "previous"}, "context":
  [
    { "key": "num_selections", "operator": "equal", "operand": 1 },
    { "key": "overlay_visible", "operator": "equal", "operand": false },
    { "key": "panel_visible", "operator": "equal", "operand": false }
  ]
},

My question is where do I put in these texts? I'm sorry if this is such a naive question. I tried to look in the .py file but couldn't find where to put this in.

**Comment by atombender** [comment]
Go til Sublime Text -> Preferences -> Key Bindings -> User. For example, you could paste this (overwriting the entire file):

```
[
{ "keys": ["escape"], "command": "alternative_autocomplete", "context":
  [
    { "key": "num_selections", "operator": "equal", "operand": 1 },
    { "key": "overlay_visible", "operator": "equal", "operand": false },
    { "key": "panel_visible", "operator": "equal", "operand": false }
  ]
},
{ "keys": ["shift+escape"], "command": "alternative_autocomplete", "args": {"cycle": "previous"}, "context":
  [
    { "key": "num_selections", "operator": "equal", "operand": 1 },
    { "key": "overlay_visible", "operator": "equal", "operand": false },
    { "key": "panel_visible", "operator": "equal", "operand": false }
  ]
}
]
```

**Comment by sivabudh** [comment]
Thanks so much!

**Comment by atombender** [comment]
The readme is correct. You pasted it wrong somehow.
