### ISSUE TITLE
Error while configuring for escape style auto-completion. (subl build 2203)

### ISSUE THREAD

**Issue by adeluccar** [atombender/sublime_text_alternative_autocompletion#12]
When I try to map the bindings as per your suggestion in [issue 11](https://github.com/alexstaubo/sublime_text_alternative_autocompletion/issues/11#issuecomment-5667729) I get the following error.

```
Error trying to parse file: Unexpected trailing characters in ~/Library/Application Support/Sublime Text 2/Packages/User/Default (OSX).sublime-keymap:7:2
```

How can I fix this? I intend to use escape style auto-completion.
Thank you!

**Comment by atombender** [comment]
Paste your full config file and should be able to help.

**Comment by adeluccar** [comment]
You should update the read me file. The fix on issue 11 works while the one on the readme file doesn't. :)

**Comment by adeluccar** [comment]
Sorry. Closed the issue by mistake. I copy-pasted the issue 11 fix on the user keymap file and it didn't throw an error when saving the file. Maybe consider updating the README with the correct code?
