### ISSUE TITLE
Error Configuring -- Unexpected Trailing Characters?

### ISSUE THREAD

**Issue by philipobrien** [atombender/sublime_text_alternative_autocompletion#13]
Hi, I'm following the Ruby on Rails (Hartl) tutorial and while setting up Sublim Text with your plugin I'm getting the following error

Error trying to parse file: Unexpected trailing characters in ~/Library/Application Support/Sublime Text 2/Packages/User/Default (OSX).sublime-keymap:7:2

I have copied the exact escape sequence code from the README to Sublime -> Preferences -> Key Bindings -> User

**Comment by atombender** [comment]
The config file needs to be valid JSON. You need to make sure that commas etc. are positioned correctly.

**Comment by philipobrien** [comment]
Sorry Alex could you elaborate a little? I'm not familiar with JSON

**Comment by atombender** [comment]
The entire config file is JSON. If you don't know JSON you will have problems generally editing Sublime Text's settings.

Anyway, here's a tip: Start with your original configuration. Then go to the top of the file, find the first `{`. Immediately _after_ the `{`, insert my example key mappings, including the last comma (`,`).

**Comment by philipobrien** [comment]
Sorted it now, thanks Alex!
