### ISSUE TITLE
Don't work with SublimeAllAutocomplete

### ISSUE THREAD

**Issue by carlosbrando** [atombender/sublime_text_alternative_autocompletion#15]
https://github.com/alienhard/SublimeAllAutocomplete

**Comment by atombender** [comment]
sublime_text_alternative_autocompletion does not use the built-in system. Therefore other modules using the built-in system will not integrate with it. Sorry.

**Comment by carlosbrando** [comment]
What is the effort to implement this feature in your plugin?

**Comment by atombender** [comment]
Don't know. I have no need for it, so I am not going to implement it.
