### ISSUE TITLE
Keybinding in Build 2217 

### ISSUE THREAD

**Issue by sandovalg** [atombender/sublime_text_alternative_autocompletion#16]
Hi having some problems with the keybindings in Build 2217 2.0.1 Release. 

{ "keys": ["escape"], "command": "alternative_autocomplete", "context":
  [
    { "key": "num_selections", "operator": "equal", "operand": 1 },
    { "key": "overlay_visible", "operator": "equal", "operand": false },
    { "key": "panel_visible", "operator": "equal", "operand": false }
  ]
},
{ "keys": ["shift+escape"], "command": "alternative_autocomplete", "args": {"cycle": "previous"}, "context":
  [
    { "key": "num_selections", "operator": "equal", "operand": 1 },
    { "key": "overlay_visible", "operator": "equal", "operand": false },
    { "key": "panel_visible", "operator": "equal", "operand": false }
  ]
}, 

Not working at all, receiving the following error:

Error trying to parse file: Unexpected character, expected a comma or closing bracket in ~/Library/Application Support/Sublime Text 2/Packages/User/Default (OSX).sublime-keymap:3:1

See my sublime-keymap (below)

[
{ "keys": ["ctrl+shift+."], "command": "erb" }
{ "keys": ["escape"], "command": "alternative_autocomplete", "context":
  [
    { "key": "num_selections", "operator": "equal", "operand": 1 },
    { "key": "overlay_visible", "operator": "equal", "operand": false },
    { "key": "panel_visible", "operator": "equal", "operand": false }
  ]
},
{ "keys": ["shift+escape"], "command": "alternative_autocomplete", "args": {"cycle": "previous"}, "context":
  [
    { "key": "num_selections", "operator": "equal", "operand": 1 },
    { "key": "overlay_visible", "operator": "equal", "operand": false },
    { "key": "panel_visible", "operator": "equal", "operand": false }
  ]
}
]

**Comment by atombender** [comment]
It needs to be valid JSON. You are missing a comma.

I have cleaned up the formatting to make it clear:

``` json
[
  {
    "keys": ["ctrl+shift+."],
    "command": "erb"
  },
  {
    "keys": ["escape"],
    "command": "alternative_autocomplete",
    "context": [
      {"key": "num_selections", "operator": "equal", "operand": 1},
      {"key": "overlay_visible", "operator": "equal", "operand": false},
      {"key": "panel_visible", "operator": "equal", "operand": false}
    ]
  },
  {
    "keys": ["shift+escape"],
    "command": "alternative_autocomplete",
    "args": {"cycle": "previous"},
    "context": [
      {"key": "num_selections", "operator": "equal", "operand": 1},
      {"key": "overlay_visible", "operator": "equal", "operand": false},
      {"key": "panel_visible", "operator": "equal", "operand": false}
    ]
  }
]
```

**Comment by sandovalg** [comment]
Alex, 

  That did it thank you!
