### ISSUE TITLE
Nothing seems to happen.

### ISSUE THREAD

**Issue by frodzet** [atombender/sublime_text_alternative_autocompletion#21]
Greetings,

Not sure if there is some settings i need to change aswell, but i used the complex tab settings inside my Key Bindings - User, however there is no differences to be seen.

The "plugin" is suppose to cycle through my tab stops rather than end it at some point, right? Well if thats the case, nothing happens.

**Comment by atombender** [comment]
Did you paste `Tabs.keymaps` into your key bindings?

**Comment by frodzet** [comment]
I did yes as i explained in my post :)

**Comment by atombender** [comment]
Works fine here with ST3. Perhaps you have something else in your prefs that override the settings?

**Comment by frodzet** [comment]
Could be yes - i'm using ST2 Build 2220, could be the problem?

**Comment by atombender** [comment]
I don't see any reason it should be a problem, as it works the same way on ST2 and ST3. I know other people use tabs, and I have not heard of anyone else having issues. Try disabling all other plugins and then removing your entire key bindings file and pasting in _only_ the contents of `Tabs.keymap`.
