### ISSUE TITLE
Sublime Text 2 Error Trailing comma before closing bracket

### ISSUE THREAD

**Issue by Bobali** [atombender/sublime_text_alternative_autocompletion#22]
![xx](https://f.cloud.github.com/assets/4492758/544482/6d289ee8-c250-11e2-820b-ec9406bf5657.jpg)
I've a big problem whit sublimr text 2 ,
whene Iclick on it : Iget this message : (Sublime Text 2 Error Trailing comma before closing bracket...)
what sould be me to do 
(sorry my english is not good :) )

**Comment by atombender** [comment]
Sounds like you should remove that last comma.

**Comment by Bobali** [comment]
he doesn't want to open :)

**Comment by atombender** [comment]
Open it in Notepad or something?

**Comment by Bobali** [comment]
hhhhh , are u serious ??
Ican't live whitout sublime text 2 :(

**Comment by atombender** [comment]
No, I mean: Open the file in Notepad, fix the problem there, then go back to Sublime.

**Comment by Bobali** [comment]
where can I find it ;)

**Comment by atombender** [comment]
The path is in the dialog box in your screenshot?

**Comment by Bobali** [comment]
thier is no foulder called Application data !!

**Comment by atombender** [comment]
`C:\Documents and Settings\Administrator\Application Data` — no? Then, inside that, `Sublime Text 2\Packages\User\Preferences.sublime-settings`.

**Comment by Bobali** [comment]
hhhhhh Ifound it thnx brooooo <3 <3 <3 <3
and I fix it , now im back to the life 
my website : http://pandc.yesegy.com
iwant your opinion on it pleaaaaaase
