### ISSUE TITLE
Autocompletion fails with ST2 Build 2126

### ISSUE THREAD

**Issue by atietje** [atombender/sublime_text_alternative_autocompletion#5]
I did a clean install of ST2 and installed [Sublime Package Control](http://wbond.net/sublime_packages/package_control) via console and restarted ST2

Next I installed sublime_text_alternative_autocompletion via Package Control. I mapped autocompletion to the escape key as described in README.md

I opened a new file and typed some words and tried to autocomplete by pressing the escape key. Nothing happened.

Before I upgraded ST2 to Build 2126 autocompletion worked. How come?

**Comment by mavuio** [comment]
same for me, did not work since Build 2125

**Comment by karl** [comment]
Also noticed this.

Would love for the plugin to be updated, it's been a life saver while transitioning from TextMate to Sublime Text!

**Comment by nigelramsay** [comment]
Same for me on build 2126

**Comment by litchfield** [comment]
Yep same again on 2126

**Comment by atombender** [comment]
The fix is simply not to check for `num_selections` in the key bindings; apparently it does not work the same way anymore. I have updated the readme file to reflect the changes required.

**Comment by atombender** [comment]
Found a problem with the current key bindings, updated the readme.
